services:
  #kq-frontend:
  #  container_name: kq-frontend
  #  build: Frontend
  #  ports:
  #    - "80:4200"
  #  volumes:
  #    - ./Frontend:/project
  #    - /project/node_modules
  kq-backend:
    container_name: kq-backend
    build: Backend
    ports:
      - "5292:80"
    depends_on:
      - kq-mongo
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
  kq-mongo:
    container_name: kq-mongo
    image: mongo:latest
    volumes:
      - kq-data:/data/db
    ports:
      - "27017:27017"
      
volumes:
  kq-data: